[tool.poetry]
name = "pyutgenerator"
version = "0.3.0"
description = ""
authors = ["shigeshige <5540474+shigeshige@users.noreply.github.com>"]

[tool.poetry.scripts]
pyutgen = 'pyutgenerator.run:main'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.0"
autopep8 = "^1.5.2"
pep8 = "^1.7.1"
flake8 = "^3.7.9"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
